H4K3ROM_BRANCH=18.1

# H4K3ROM RELEASE VERSION
H4K3ROM_VERSION_MAJOR = 1
H4K3ROM_VERSION_MINOR = 0
H4K3ROM_VERSION_MAINTENANCE = 0

PRODUCT_VERSION_MAJOR := $(H4K3ROM_VERSION_MAJOR)
PRODUCT_VERSION_MINOR := $(H4K3ROM_VERSION_MINOR)
PRODUCT_VERSION_MAINTENANCE := $(H4K3ROM_VERSION_MAINTENANCE)

VERSION := $(H4K3ROM_VERSION_MAJOR).$(H4K3ROM_VERSION_MINOR)

ifndef H4K3ROM_BUILDTYPE
    ifdef RELEASE_TYPE
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^H4K3ROM_||g')
        H4K3ROM_BUILDTYPE := $(RELEASE_TYPE)
    else
        H4K3ROM_BUILDTYPE := TEST
    endif
endif

ifdef H4K3ROM_BUILDTYPE
    ifeq ($(H4K3ROM_BUILDTYPE), NIGHTLY)
        H4K3ROM_VERSION := $(TARGET_PRODUCT)_$(H4K3ROM_BRANCH)-$(VERSION)-NIGHTLY-$(shell date -u +%Y%m%d)
    endif
    ifeq ($(H4K3ROM_BUILDTYPE), WEEKLY)
       H4K3ROM_VERSION := $(TARGET_PRODUCT)_$(H4K3ROM_BRANCH)-$(VERSION)-WEEKLY-$(shell date -u +%Y%m%d)
    endif
    ifeq ($(H4K3ROM_BUILDTYPE), EXPERIMENTAL)
        H4K3ROM_VERSION := $(TARGET_PRODUCT)_$(H4K3ROM_BRANCH)-$(VERSION)-EXPERIMENTAL-$(shell date -u +%Y%m%d)
    endif
    ifeq ($(H4K3ROM_BUILDTYPE), UNOFFICIAL)
        H4K3ROM_VERSION := $(TARGET_PRODUCT)_$(H4K3ROM_BRANCH)-$(VERSION)-UNOFFICIAL-$(shell date -u +%Y%m%d)
    endif
else
#We reset back to UNOFFICIAL
        H4K3ROM_VERSION := $(TARGET_PRODUCT)_$(H4K3ROM_BRANCH)-$(VERSION)-UNOFFICIAL-$(shell date -u +%Y%m%d)
endif
